name       : libtifiles
version    : 1.1.7
release    : 1
source     :
    - https://downloads.sourceforge.net/project/tilp/tilp2-linux/tilp2-1.18/libtifiles2-1.1.7.tar.bz2 : 9ac63b49e97b09b30b37bbc84aeb15fa7967bceb944e56141c5cd5a528acc982
license    : GPL-2.0-or-later
component  : programming.library
summary    : TiLP file library
description: |
    This library is part of the TiLP project.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(ticonv)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
